# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import src.apps.categories.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('cost', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, upload_to=src.apps.categories.models.make_id)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='categories.ServiceCategory'),
        ),
    ]
