# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 17:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('special', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='_displayitem_categories_+', to='categories.ServiceCategory')),
            ],
        ),
    ]
