# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 17:50
from __future__ import unicode_literals

from django.db import migrations, models

import src.apps.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0002_displayitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayitem',
            name='image',
            field=models.ImageField(blank=True,
                                    upload_to=src.apps.core.utils.Folders.display_items),
        ),
    ]
