# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import src.apps.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_displayitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayitem',
            name='image',
            field=models.ImageField(null=True, upload_to=src.apps.core.utils.Folders.display_items),
        ),
        migrations.AlterField(
            model_name='displayitem',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='displayitem',
            name='special',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
