# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20171024_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayitem',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
