# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20171024_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='_service_recommendations_+', to='categories.Service'),
        ),
    ]
