# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import src.apps.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('avatar', models.ImageField(upload_to=src.apps.core.utils.Folders.avatars)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='F', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('rating', models.FloatField(default=0.0)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masters.Location')),
                ('services', models.ManyToManyField(related_name='masters', to='categories.Service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', related_query_name='master', to='authentication.PhoneAuthUser')),
            ],
            options={
                'db_table': 'master',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=src.apps.core.utils.Folders.portfolio)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='masters.Master')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='masters.Master')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('value', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='masters.Schedule')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masters.Time')),
            ],
        ),
    ]
