# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import src.apps.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0008_auto_20170921_1218'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street_name', models.CharField(max_length=64)),
                ('building', models.CharField(max_length=16)),
                ('floor', models.IntegerField()),
                ('apt_number', models.IntegerField()),
                ('entrance', models.IntegerField()),
                ('has_intercom', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('avatar', models.ImageField(upload_to=src.apps.core.utils.Folders.avatars)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='F', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('tip', models.IntegerField(default=5)),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='masters.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', related_query_name='client', to='authentication.PhoneAuthUser')),
            ],
            options={
                'db_table': 'client',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('avatar', models.ImageField(upload_to=src.apps.core.utils.Folders.avatars)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='F', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masters.Location')),
                ('services', models.ManyToManyField(related_name='masters', to='categories.Service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', related_query_name='master', to='authentication.PhoneAuthUser')),
            ],
            options={
                'db_table': 'master',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='masters.Master')),
                ('times', models.ManyToManyField(through='masters.Availability', to='masters.Time')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Time'),
        ),
        migrations.AddField(
            model_name='availability',
            name='working_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.WorkingHours'),
        ),
    ]
