# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='apt_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='building',
        ),
        migrations.RemoveField(
            model_name='address',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='address',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='address',
            name='has_intercom',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='masters.Address'),
        ),
    ]
