# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:28
from __future__ import unicode_literals

from datetime import date, datetime, time, timedelta

from django.db import migrations


def create_time_instances(apps, schema_editor):
    Time = apps.get_model('masters', 'Time')
    end_time = datetime.combine(date.today(), time(23, 0))
    current_time = datetime.combine(date.today(), time(8, 0))

    while current_time < end_time:
        Time.objects.create(hour=current_time.hour, minute=current_time.minute)
        current_time = current_time + timedelta(minutes=30)


class Migration(migrations.Migration):
    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_time_instances)
    ]
