# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20171009_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='value',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
    ]
