# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_auto_20171017_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='about',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
