# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_master_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='status',
            field=models.CharField(choices=[('ON_MODERATION', 'На модерации'), ('ACCEPTED', 'Принято')], default='ON_MODERATION', max_length=13),
        ),
    ]
