# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_master_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='status',
            field=models.CharField(choices=[('DUMMY', 'Свежий мастер'), ('ON_REVIEW', 'На модерации'), ('VEFIRIED', 'Подтверждён')], default='DUMMY', max_length=9),
        ),
    ]
