# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_master_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Location'),
        ),
    ]
