# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_address_comment'),
        ('masters', '0009_auto_20171114_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.Client')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='masters.Master')),
            ],
        ),
    ]
