# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.CharField(choices=[('DUMMY', 'Свежий мастер'), ('ON_REVIEW', 'На модерации'), ('VERIFIED', 'Подтверждён')], default='DUMMY', max_length=9),
        ),
    ]
