# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_auto_20171119_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future', models.IntegerField(default=0)),
                ('on_hold', models.IntegerField(default=0)),
                ('sent', models.IntegerField(default=0)),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='masters.Master')),
            ],
        ),
    ]
