# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='sent',
            new_name='transferred',
        ),
    ]
