# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_auto_20171202_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
