# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_portfolioimage_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.CharField(choices=[('DUMMY', 'Свежий мастер'), ('ON_REVIEW', 'На модерации'), ('DELETED', 'Удалён'), ('BLOCKED', 'Заблокирован'), ('VERIFIED', 'Подтверждён')], default='DUMMY', max_length=9),
        ),
    ]
