# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_auto_20171219_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='debt',
            field=models.IntegerField(default=0),
        ),
    ]
