# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_auto_20180120_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
