version: "3.0"

services:
  app:
    image: bigblackbug/4hands2go-app:latest
    environment:
        - DJANGO_SETTINGS_MODULE=src.config.settings.local
        - DATABASE_HOST=pg
        - DATABASE_NAME=4hands2go_local
        - DATABASE_USER=4hands2go_local
        - DATABASE_PASSWORD=4hands2go_local
        - DJANGO_RUN_MIGRATIONS=yes
        - DJANGO_RUN_COLLECTSTATIC=yes
        - DJANGO_RUN_CREATESUPERUSER=yes
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - ADMIN_USERNAME=${ADMIN_USERNAME}
    ports:
      - "${DEPLOY_PORT-8000}:8000"
    links:
      - pg
    volumes:
      - ~/4hands2go-local-media-data:/code/media

  pg:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=4hands2go_local
      - POSTGRES_PASSWORD=4hands2go_local
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ~/4hands2go-local-data:/var/lib/postgresql/data/pgdata
