version: "3.0"

services:
  app:
    image: bigblackbug/4hands2go-app:latest
    environment:
        - DJANGO_SETTINGS_MODULE=src.config.settings.dev
        - DATABASE_URL=postgres://4hands2go_dev:4hands2go_dev@pg/4hands2go_dev
        - DATABASE_HOST=pg
        - DATABASE_NAME=4hands2go_dev
        - DATABASE_USER=4hands2go_dev
        - DATABASE_PASSWORD=4hands2go_dev
        - DJANGO_RUN_MIGRATIONS=yes
    ports:
      - "${DEPLOY_PORT-8000}:8000"
    links:
      - pg

  pg:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=4hands2go_dev
      - POSTGRES_PASSWORD=4hands2go_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/4hands2go-dev-data:/var/lib/postgresql/data/pgdata
