version: "3.0"

services:
  nginx:
    image: bigblackbug/4hands2go-nginx:dev
    links:
      - app
    ports:
      - ${DEPLOY_PORT-8000}:80
      - ${DEPLOY_HTTPS_PORT-4433}:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
#      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /var/lib/4hands2go/dev-media:/var/lib/4hands2go/media

# app is available on port 8000 by default
  app:
    image: bigblackbug/4hands2go-app:latest
    environment:
        - DJANGO_SETTINGS_MODULE=src.config.settings.dev
        - DATABASE_URL=postgres://4hands2go_dev:4hands2go_dev@pg/4hands2go_dev
        - DATABASE_HOST=pg
        - DATABASE_NAME=4hands2go_dev
        - DATABASE_USER=4hands2go_dev
        - DATABASE_PASSWORD=4hands2go_dev
        - DJANGO_RUN_MIGRATIONS=yes
    links:
      - pg
    volumes:
      - /var/lib/4hands2go/dev-media:/code/media


  pg:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=4hands2go_dev
      - POSTGRES_PASSWORD=4hands2go_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/4hands2go/dev-db-data:/var/lib/postgresql/data/pgdata
