version: "3.0"

services:
  nginx:
    image: bigblackbug/4hands2go-nginx:dev
    links:
      - app
    ports:
      - ${DEPLOY_PORT-80}:80
      - ${DEPLOY_HTTPS_PORT-443}:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/4hands2go/dev-media:/var/lib/4hands2go/media
      - /var/lib/4hands2go/dev-static:/var/lib/4hands2go/static

# app is available on port 8000 by default
  app:
    image: bigblackbug/4hands2go-app:latest
    environment:
        - DJANGO_SETTINGS_MODULE=src.config.settings.dev
        - DATABASE_HOST=pg
        - DATABASE_NAME=4hands2go_dev
        - DATABASE_USER=4hands2go_dev
        - DATABASE_PASSWORD=4hands2go_dev
        - DJANGO_RUN_MIGRATIONS=yes
        - DJANGO_RUN_CREATESUPERUSER=yes
        - DJANGO_RECREATE_TEST_DATA=${DJANGO_RECREATE_TEST_DATA-no}
        # needed for admin pages
        - DJANGO_RUN_COLLECTSTATIC=yes
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - ADMIN_USERNAME=${ADMIN_USERNAME}
        # temporarily disabling 'time of commute' calculations
        - USE_GMAPS_API=${USE_GMAPS_API-False}
        # logging
        - LOG_FOLDER=/code/logs
        - LOG_LEVEL=${LOG_LEVEL-DEBUG}
        - SENTRY_URL=https://7dd35167ff334e0a8649804d93b9f90a:8f49d425079343de95ee1a7de50ba1e4@sentry.io/272430
    links:
      - pg
    volumes:
      - /var/logs/4hands2go/dev:/code/logs
      - /var/lib/4hands2go/dev-media:/code/media
      - /var/lib/4hands2go/dev-static:/code/static

  pg:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=4hands2go_dev
      - POSTGRES_PASSWORD=4hands2go_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - /var/lib/4hands2go/dev-db-data:/var/lib/postgresql/data/pgdata

  mgmt:
    image: beinlife/4hands2go-admin
