version: "3.0"

services:
  nginx:
    image: bigblackbug/4hands2go-nginx:dev
    links:
      - app
    ports:
      - ${DEPLOY_PORT-8000}:80
      - ${DEPLOY_HTTPS_PORT-4433}:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
#      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /var/lib/4hands2go/dev-media:/var/lib/4hands2go/media
      - /var/lib/4hands2go/dev-static:/var/lib/4hands2go/static

# TODO gotta change ownership of the media folder on the host to the current user
# app is available on port 8000 by default
  app:
    image: bigblackbug/4hands2go-app:latest
    environment:
        - DJANGO_SETTINGS_MODULE=src.config.settings.dev
        - DATABASE_HOST=pg
        - DATABASE_NAME=4hands2go_dev
        - DATABASE_USER=4hands2go_dev
        - DATABASE_PASSWORD=4hands2go_dev
        - DJANGO_RUN_MIGRATIONS=yes
        - DJANGO_RUN_CREATESUPERUSER=yes
        - DJANGO_RECREATE_TEST_DATA=yes
        # needed for admin pages
        - DJANGO_RUN_COLLECTSTATIC=yes
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - ADMIN_USERNAME=${ADMIN_USERNAME}
        - OWNER_USER_GROUP=${OWNER_USER_GROUP}
        # temporarily disabling 'time of commute' calculations
        - USE_GMAPS_API=False
    links:
      - pg
    volumes:
      - /var/lib/4hands2go/dev-media:/code/media
      - /var/lib/4hands2go/dev-static:/code/static

  pg:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=4hands2go_dev
      - POSTGRES_PASSWORD=4hands2go_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/4hands2go/dev-db-data:/var/lib/postgresql/data/pgdata
