# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:39
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='expires',
            field=models.DateTimeField(
                default=datetime.datetime(2017, 10, 17, 8, 44, 46, 440966,
                                          tzinfo=utc), editable=False),
        ),
    ]
