# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 20, 18, 53, 464278, tzinfo=utc), editable=False),
        ),
    ]
