# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40, unique=True)),
                ('verification_code', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='phoneauthuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='phoneauthuser',
            name='password',
        ),
    ]
