# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20171118_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('MASTER', 'Master'), ('CLIENT', 'Client')], default=None, max_length=6),
            preserve_default=False,
        ),
    ]
