# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170914_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='verification_code',
            field=models.CharField(max_length=4),
        ),
    ]
