# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 16, 10, 18, 16, 631305), editable=False),
        ),
    ]
