# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_registration_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 16, 10, 31, 53, 302682, tzinfo=utc), editable=False),
        ),
    ]
