# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 20:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import src.apps.core.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street_name', models.CharField(max_length=64)),
                ('building', models.CharField(max_length=16)),
                ('floor', models.IntegerField()),
                ('apt_number', models.IntegerField()),
                ('entrance', models.IntegerField()),
                ('has_intercom', models.BooleanField()),
                ('location', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='+', to='core.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('avatar', models.ImageField(blank=True, null=True,
                                             upload_to=src.apps.core.utils.Folders.avatars)),
                ('gender',
                 models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')],
                                  default='F', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('tip', models.IntegerField(default=5)),
                ('address', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='client', to='clients.Address')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='client', related_query_name='client',
                    to='authentication.PhoneAuthUser')),
            ],
            options={
                'db_table': 'client',
                'abstract': False,
            },
        ),
    ]
