# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20171023_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptogram', models.CharField(max_length=64)),
                ('client_name_on_card', models.CharField(max_length=64)),
                ('card_number', models.CharField(max_length=19)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to='clients.Client')),
            ],
        ),
    ]
