# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_address_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('DUMMY', 'Свежий аккаунт'), ('CREATED', 'Подтверждён')], default='DUMMY', max_length=9),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
