# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20171119_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('DUMMY', 'Свежий аккаунт'), ('VERIFIED', 'Подтверждён')], default='DUMMY', max_length=9),
        ),
    ]
