# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20171123_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='cryptogram',
            field=models.CharField(max_length=512),
        ),
    ]
