# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20180126_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='title',
        ),
    ]
