# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 16:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPaymentsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(unique=True)),
                ('transaction_info',
                 django.contrib.postgres.fields.hstore.HStoreField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True,
                                       on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='order',
                                       to='orders.CloudPaymentsTransaction'),
        ),
    ]
