# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_auto_20171028_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(
                choices=[('CARD', 'Карта'), ('CASH', 'Наличные')],
                default='CARD', max_length=4),
        ),
    ]
