# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudpaymentstransaction',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='cloudpaymentstransaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('FINISHED', 'Завершена'), ('S3D_FAILED', 'Ошибка верификации Secure 3D')], default='CREATED', max_length=10),
        ),
    ]
