# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20171030_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_taken',
            field=models.DurationField(null=True),
        ),
    ]
