# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20171111_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='locked',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='locked',
            field=models.BooleanField(),
        ),
    ]
