# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20171112_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('STARTED', 'Начат'), ('DONE', 'Завершён')], default='CREATED', max_length=8),
        ),
    ]
