# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20171124_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Принят Мастером'), ('STARTED', 'Начат'), ('DONE', 'Завершён')], default='ACCEPTED', max_length=8),
        ),
    ]
