# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0015_auto_20171219_1603'),
        ('orders', '0011_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('IN', 'Зачисление'), ('OUT', 'Отчисление')], default='IN', max_length=3)),
                ('value', models.PositiveIntegerField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.Master')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.Order')),
            ],
        ),
    ]
